# build
# docker build --tag uryyyyyyy/alpine-nodejs-yarn-sbt-mysqlclient:0.2.0 ./

# run
# docker run --rm uryyyyyyy/alpine-nodejs-yarn-sbt-mysqlclient:0.2.0 mysql

FROM uryyyyyyy/alpine-nodejs-yarn-sbt:0.2.0

RUN apk add --no-cache mysql-client
